language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.5
  - 2.4.2
gemfile:
  - Gemfile
  - gemfiles/activemodel-3.2.gemfile
  - gemfiles/activemodel-4.2.gemfile
  - gemfiles/activemodel-5.1.gemfile
  - gemfiles/activemodel-5.2.gemfile
  - gemfiles/activemodel-master.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/activemodel-master.gemfile
  fast_finish: true
