language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
gemfile:
  - Gemfile
  - gemfiles/activemodel-3.2.gemfile
  - gemfiles/activemodel-4.2.gemfile
  - gemfiles/activemodel-master.gemfile
matrix:
  fast_finish: true
