language: ruby
cache: bundler
sudo: false
rvm:
  - 2.1
  - 2.2
  # - 2.3
  - jruby-19mode
gemfile:
  - Gemfile
  - gemfiles/activemodel-3.2.gemfile
  - gemfiles/activemodel-4.1.gemfile
  - gemfiles/activemodel-4.2.gemfile
  - gemfiles/activemodel-master.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/activemodel-master.gemfile
