language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
gemfile:
  - Gemfile
  - gemfiles/activemodel-3.1.gemfile
  - gemfiles/activemodel-3.2.gemfile
  - gemfiles/activemodel-4.0.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/activemodel-4.0.gemfile
