language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby-19mode
gemfile:
  - Gemfile
  - gemfiles/activemodel-3.1.gemfile
  - gemfiles/activemodel-3.2.gemfile
  - gemfiles/activemodel-4.0.gemfile
  - gemfiles/activemodel-master.gemfile
matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/activemodel-3.1.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/activemodel-3.2.gemfile
  allow_failures:
    - gemfile: gemfiles/activemodel-master.gemfile
