language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
gemfile:
  - Gemfile
  - gemfiles/activemodel-3.1.gemfile
  - gemfiles/activemodel-3.2.gemfile
  - gemfiles/activemodel-master.gemfile