language: ruby
cache: bundler
sudo: false
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
gemfile:
  - Gemfile
  - gemfiles/activemodel-3.2.gemfile
  - gemfiles/activemodel-4.1.gemfile
  - gemfiles/activemodel-4.2.gemfile
  - gemfiles/activemodel-master.gemfile
